---
    name: CI
    
    on:
      push:
    
    jobs:
      test:
        name: Test
        runs-on: ubuntu-24.04
    
        steps:
          - name: Install dependencies
            run: |
              sudo apt-get update -qq
              export DEBIAN_FRONTEND=noninteractive
              sudo apt-get install -y --no-install-recommends software-properties-common apt-utils ccache clang lld llvm python3 python3-pip pipx
              pipx install ninja
    
          - name: Check out repository code
            uses: actions/checkout@v4
    
          - name: Install xmake
            uses: xmake-io/github-action-setup-xmake@v1
            with:
              xmake-version: 'latest'
              actions-cache-folder: '.xmake-cache'
    
          - name: Build
            run: |
              xmake f -y

          - name: Test
            run: |
              xmake test
